server:
  http:
    addr: 127.0.0.1:8000
    timeout: 600
  grpc:
    addr: 127.0.0.1:9000
    timeout: 600
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/medical_db?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

